// <auto-generated />
namespace RRDv2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class nullable_roomtype : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nullable_roomtype));
        
        string IMigrationMetadata.Id
        {
            get { return "201504171623145_nullable_roomtype"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
